import { useState } from 'react';
import { User } from '@supabase/supabase-js';
import { useLanguageNavigation } from '@/hooks/useLanguageNavigation';
import { CreateProjectFormData } from '@/lib/validators/project';
import { ProjectService, ProjectOperationData } from '@/services/projectService';
import { DatabaseProject } from '@/hooks/projectTypes';
import { toast } from 'sonner';
import { useT } from '@/lib/i18n';

interface UseProjectSubmissionOptions {
  mode: 'create' | 'edit';
  user: User | null;
  existingProject?: DatabaseProject;
  saveAsTemplate: boolean;
  setSaveAsTemplate: (value: boolean) => void;
}

export const useProjectSubmission = (options: UseProjectSubmissionOptions) => {
  const { mode, user, existingProject, saveAsTemplate, setSaveAsTemplate } = options;
  const { navigate } = useLanguageNavigation();
  const t = useT();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const projectService = new ProjectService(user);

  const saveTemplate = async (templateData: {
    name: string;
    brief: string;
    contract_required?: boolean;
    payment_proof_required?: boolean;
    contract_terms?: string;
    payment_terms?: string;
    project_scope?: string;
    revision_policy?: string;
    milestones: Array<{
      title: string;
      description: string;
      price: number;
    }>;
  }): Promise<boolean> => {
    if (!user) {
      toast.error(t('mustBeLoggedInToSaveTemplate'));
      return false;
    }

    try {
      await projectService.saveAsTemplate({
        id: '', // Will be generated by the service
        name: templateData.name,
        brief: templateData.brief,
        contract_required: templateData.contract_required || false,
        payment_proof_required: templateData.payment_proof_required || false,
        contract_terms: templateData.contract_terms,
        payment_terms: templateData.payment_terms,
        project_scope: templateData.project_scope,
        revision_policy: templateData.revision_policy,
        milestones: templateData.milestones.map(milestone => ({
          ...milestone,
          start_date: '',
          end_date: ''
        })),
        user_id: user.id,
      });
      
      toast.success(t('templateSavedSuccessfully'));
      return true;
    } catch (error) {
      toast.error(t('failedToSaveTemplate'));
      return false;
    }
  };

  const handleSubmit = async (data: CreateProjectFormData) => {
    if (!user) {
      toast.error(t('mustBeLoggedIn'));
      return;
    }

    setIsSubmitting(true);
    
    try {
      // Prepare project data
      const projectData: ProjectOperationData = {
        ...data,
        ...(mode === 'edit' && existingProject && {
          id: existingProject.id,
          slug: existingProject.slug,
        }),
      };

      // Save project
      const result = await projectService.saveProject(projectData, mode);
      
      if (!result) {
        throw new Error(`Failed to ${mode} project`);
      }

      // Save as template if requested (only for create mode)
      if (mode === 'create' && saveAsTemplate) {
        await projectService.saveAsTemplate({
          id: '', // Will be generated by Supabase
          name: `${data.name} Template`,
          brief: data.brief,
          contract_required: data.contractRequired,
          payment_proof_required: data.paymentProofRequired,
          contract_terms: data.contractTerms,
          payment_terms: data.paymentTerms,
          project_scope: data.projectScope,
          revision_policy: data.revisionPolicy,
          milestones: data.milestones.map(m => ({
            title: m.title,
            description: m.description,
            price: m.price,
            start_date: m.start_date || '',
            end_date: m.end_date || '',
          })),
        });
        toast.success(t('templateSavedSuccessfully'));
      }

      // Show success message
      toast.success(
        mode === 'create' 
          ? t('projectCreatedSuccessfully') 
          : 'Project updated successfully'
      );

      // Navigate to appropriate page
      if (mode === 'create') {
        navigate(`/project/${result.slug}`);
      } else {
        navigate('/projects');
      }

    } catch (error) {
      toast.error(error instanceof Error ? error.message : t('errorOccurred'));
    } finally {
      setIsSubmitting(false);
    }
  };

  return {
    isSubmitting,
    handleSubmit,
    saveTemplate,
    saveAsTemplate,
    setSaveAsTemplate,
  };
};