import { useState, useEffect } from 'react';
import { User } from '@supabase/supabase-js';
import { ProjectTemplate } from '@/types/projectTemplate';
import { ServiceRegistry } from '@/services/core/ServiceRegistry';
import { toast } from 'sonner';

interface UseTemplatesProps {
  user: User | null;
}

export const useTemplates = ({ user }: UseTemplatesProps) => {
  const [templates, setTemplates] = useState<ProjectTemplate[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const serviceRegistry = ServiceRegistry.getInstance();
  const projectService = serviceRegistry.getProjectService(user);

  const fetchTemplates = async () => {
    if (!user) {
      setTemplates([]);
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const fetchedTemplates = await projectService.getTemplates();
      setTemplates(fetchedTemplates);
    } catch (error) {
      setError('Failed to fetch templates');
      toast.error('Failed to fetch templates');
    } finally {
      setLoading(false);
    }
  };

  const saveTemplate = async (templateData: {
    name: string;
    brief: string;
    contract_required?: boolean;
    payment_proof_required?: boolean;
    contract_terms?: string;
    payment_terms?: string;
    project_scope?: string;
    revision_policy?: string;
    milestones: Array<{
      title: string;
      description: string;
      price: number;
    }>;
  }): Promise<boolean> => {
    if (!user) {
      toast.error('You must be logged in to save a template');
      return false;
    }

    try {
      await projectService.saveAsTemplate({
        id: '', // Will be generated by the service
        name: templateData.name,
        brief: templateData.brief,
        contract_required: templateData.contract_required || false,
        payment_proof_required: templateData.payment_proof_required || false,
        contract_terms: templateData.contract_terms,
        payment_terms: templateData.payment_terms,
        project_scope: templateData.project_scope,
        revision_policy: templateData.revision_policy,
        milestones: templateData.milestones.map(milestone => ({
          ...milestone,
          start_date: '',
          end_date: ''
        })),
        user_id: user.id,
      });
      
      toast.success('Template saved successfully');
      await fetchTemplates();
      return true;
    } catch (error) {
      toast.error('Failed to save template');
      return false;
    }
  };

  const deleteTemplate = async (templateId: string): Promise<boolean> => {
    if (!user) {
      toast.error('You must be logged in to delete a template');
      return false;
    }

    try {
      await projectService.deleteTemplate(templateId);
      await fetchTemplates();
      toast.success('Template deleted successfully');
      return true;
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to delete template';
      toast.error(errorMessage);
      return false;
    }
  };

  // Load templates when user changes
  useEffect(() => {
    fetchTemplates();
  }, [user]);

  return {
    templates,
    loading,
    error,
    fetchTemplates,
    saveTemplate,
    deleteTemplate,
  };
};