
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { CreateProjectFormData } from '@/lib/validators/project';
import { calculateProjectDates } from '@/lib/projectDateUtils';

export const useCreateProjectSubmission = () => {
  const navigate = useNavigate();

  const handleSubmit = useCallback(async (data: CreateProjectFormData) => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        toast.error('You must be logged in to create a project');
        return;
      }

      console.log('Creating project for user:', user.id);

      // Get user profile to check current status
      const { data: profile, error: profileError } = await supabase
        .from('profiles')
        .select('user_type, project_count, full_name')
        .eq('id', user.id)
        .single();

      if (profileError) {
        console.error('Error fetching user profile:', profileError);
        toast.error('Failed to check user profile');
        return;
      }

      console.log('User profile:', profile);

      // Get actual project count to verify accuracy
      const { data: actualProjects, error: projectsError } = await supabase
        .from('projects')
        .select('id')
        .eq('user_id', user.id);

      if (projectsError) {
        console.error('Error fetching actual projects:', projectsError);
      } else {
        console.log('Actual project count:', actualProjects?.length || 0);
        console.log('Profile project count:', profile.project_count);
      }

      // Get user limits
      const { data: limits, error: limitsError } = await supabase
        .rpc('get_user_limits', {
          _user_type: profile.user_type || 'free'
        });

      if (limitsError) {
        console.error('Error getting user limits:', limitsError);
      } else {
        console.log('User limits:', limits);
      }

      // Check project limits before creating
      const { data: limitCheck, error: limitError } = await supabase
        .rpc('check_user_limits', {
          _user_id: user.id,
          _action: 'project'
        });

      console.log('Limit check result:', limitCheck);
      console.log('Limit check error:', limitError);

      if (limitError) {
        console.error('Error checking limits:', limitError);
        toast.error('Failed to check project limits');
        return;
      }

      if (!limitCheck) {
        const userType = profile.user_type || 'free';
        const currentCount = profile.project_count || 0;
        const maxProjects = userType === 'plus' ? 3 : userType === 'pro' ? 10 : 1;
        
        toast.error(`Project limit reached (${currentCount}/${maxProjects}). Please upgrade your plan to create more projects.`);
        return;
      }

      // Calculate project dates from milestones
      const { start_date, end_date } = calculateProjectDates(data.milestones);

      // Create the project (slug will be auto-generated by database trigger)
      const { data: project, error: projectError } = await supabase
        .from('projects')
        .insert({
          name: data.name,
          brief: data.brief,
          client_email: data.clientEmail,
          user_id: user.id,
          start_date,
          end_date,
          slug: '', // Temporary value, will be overwritten by trigger
        })
        .select()
        .single();

      if (projectError) throw projectError;

      console.log('Project created:', project);

      // Create milestones
      const milestoneInserts = data.milestones.map((milestone) => ({
        project_id: project.id,
        title: milestone.title,
        description: milestone.description,
        price: milestone.price,
        status: 'pending' as const,
        start_date: milestone.start_date || null,
        end_date: milestone.end_date || null,
      }));

      const { error: milestonesError } = await supabase
        .from('milestones')
        .insert(milestoneInserts);

      if (milestonesError) throw milestonesError;

      // Update project count
      const { error: updateError } = await supabase
        .rpc('update_project_count', {
          _user_id: user.id,
          _count_change: 1
        });

      if (updateError) {
        console.error('Error updating project count:', updateError);
      } else {
        console.log('Project count updated successfully');
      }

      toast.success('Project created successfully!');
      navigate('/dashboard');
    } catch (error) {
      console.error('Error creating project:', error);
      toast.error('Failed to create project. Please try again.');
    }
  }, [navigate]);

  return {
    handleSubmit,
  };
};
